# https://3dprintbeginner.com/3d-printer-farm-with-octoprint-and-docker/

version: '3.9'

services:
    klipper:
      image: m3dp/komf-stack
      build:
        dockerfile: ./docker/Dockerfile
        context: .
      # if klipper cannot connect to the printer check permissions on rpi then add the group here
      # group_add:
      #   - "996"
      #   - "998"
      cap_add:
        - SYS_NICE
      container_name: komf-e5p
      ports:
        - 7125:7125
        - 5000:5000
        - 8080:8080
        - 8010:80
        - 8011:80
      restart: unless-stopped
      volumes:
        - e5p_data:/home/m3dp
      devices:
        - /dev/ender5plus:/dev/ttyACM0

volumes: 
  e5p_data:
