# https://3dprintbeginner.com/3d-printer-farm-with-octoprint-and-docker/

version: '3.9'
 services: 
 Octoprint
 octoprint1:
      container_name: Octoprint1
      image: octoprint/octoprint
      hostname: Octoprint1
      restart: unless-stopped
      ports:
        - 5000:5000
        - 8080:8080
      volumes:
        - /home/dietpi/docker/octoprint1:/octoprint1
      environment:
        - ENABLE_MJPG_STREAMER=true
        - MJPG_STREAMER_INPUT=-n -d /dev/video0:/dev/video0 -r 1280x720 -f 30
      devices:
      #Printer Port
        - /dev/ttyACM0:/dev/ttyACM0
      #Webcam port
      #  - /dev/video0:/dev/video0
  #####Octoprint2
   octoprint2:
      container_name: Octoprint2
      image: octoprint/octoprint
      hostname: Octoprint2
      restart: unless-stopped
      ports:
        - 5001:5000
        - 8081:8080
      volumes:
        - /home/dietpi/docker/octoprint2:/octoprint2
      environment:
        - ENABLE_MJPG_STREAMER=true 
        - MJPG_STREAMER_INPUT=-n -d /dev/video0:/dev/video1 -r 1280x720 -f 30
      devices:
      #Printer Port
        - /dev/ttyACM0:/dev/ttyACM1
      #Webcam port
      # - /dev/video0:/dev/video1